### PR TITLE
Codeowners

### PR DESCRIPTION
**Pull request by Mykell404**
# Description

I added my name to the codeowners file

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Reviewing this right now, let's see...

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Seems like the `CODEOWNERS` file is missing the right content. Could you fix that and push the changes?

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Oh looks like the `CODEOWNERS` file I gave you is outdated. It has **Carl listed**, but he's... no longer with the company. Could you **remove him from the file**, but not from our hearts, and push that change?

**Comment by Mykell404** [comment]
I have fix the changes

**Comment by Mykell404** [comment]
I have removed **carl's** name from the file

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Seems like the `CODEOWNERS` file is missing the right content. Could you fix that and push the changes?

**Comment by Mykell404** [comment]
i have fixed the file

**Comment by Mykell404** [comment]
fixed the issues, please merge

**Comment by Mykell404** [comment]
Fixed changes

**Pull request closed without merging**
